jasypt:
  encryptor:
    password: myEncryptionKey123
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  jackson:
    time-zone: Asia/Singapore
  cache:
    type: redis
  datasource:
    url: jdbc:mysql://intruder-detection-db.c9jun6t2d9uf.us-east-1.rds.amazonaws.com:3306/idss?serverTimezone=UTC
    username: admin
    password: ENC(roSgzaPIjSh46neDANSBDRsppy2Q8C9A)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
cloud:
  aws:
    credentials:
      access-key: ENC(vyrSk9gLGrFSB6NUIFAyXPB3il9BgYvvtd06wbT5qLk=)
      secret-key: ENC(jlwUFwwF4JwAOVK1yKqnvlveWB81fNSjPZmp7sEol4IbgK6AaljOLX39mveOs0PJENEZeCxNYjo=)
    region:
      static: us-east-1
  accessKeyId:
  secretAccessKey:
server:
  ssl:
    enabled: true
    key-store: file:/opt/certs/keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: springboot-https
