spring:
  datasource:
    url: jdbc:mysql://intruder-detection-db.c9jun6t2d9uf.us-east-1.rds.amazonaws.com:3306/idss
    username: admin
    password: 930485bd7ncxbh
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  security:
    oauth2:
      resourceserver:
        jwt:
          jwt-set-uri: none
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
